# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-29 02:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20160828_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='full_name',
        ),
    ]
