# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='puzzle',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='solution',
            name='puzzle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='puzzles.Puzzle'),
        ),
    ]
