# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0002_auto_20160816_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='text',
            field=models.CharField(max_length=255),
        ),
    ]
