# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzles', '0004_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
